name: Deploy app

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted
    needs: prepare-environment
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Stop and remove container
        run: docker compose down
      - name: Build and start container
        run: docker compose up -d --build
